arrowParens: always
bracketSameLine: false
bracketSpacing: true
jsxSingleQuote: true
proseWrap: always
quoteProps: as-needed
semi: true
singleQuote: true
tabWidth: 2
trailingComma: all
printWidth: 120
useTabs: false
endOfLine: 'lf'
